main_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from main_app import views

app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('<path:url>?<str:selected>', views.show_selected, name='select'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),

]

main_app/models.py
from django.db import models


# Create your models here.
class Menu(models.Model):
    name = models.CharField(max_length=255, help_text='Name of menu item', null=False, unique=True)
    url = models.CharField(default='menu/', max_length=255)
    left = models.IntegerField(blank=True, null=True)
    right = models.IntegerField(blank=True, null=True)
    parent = models.ForeignKey(to='self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    level = models.IntegerField(blank=True, null=True)
    root = models.ForeignKey(to='self', blank=True, null=True, related_name='head', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super(Menu, self).save(*args, **kwargs)
        self.set_mptt()

    def set_mptt(self, left=1, parent=None, level=1, root=None):
        for i in type(self).objects.filter(parent=parent):
            if i.parent is None:
                root = i
            obj, children_count = i, 0
            while obj.children.exists():
                for child in obj.children.all():
                    children_count += 1
                    obj = child
            data = {
                'level': level,
                'left': left,
                'right': left + (children_count * 2) + 1,
                'root': root
            }
            type(self).objects.filter(id=i.id).update(**data)
            left = data['right'] + 1
            self.set_mptt(left=data['left'] + 1, parent=i.id, level=data['level'] + 1, root=root)

    def __str__(self):
        return self.name

    def display_children(self):
        return '\n'.join(child.name for child in self.children.all())

    def display_parent(self):
        return '\n'.join(item.name for item in Menu.objects.all())

    def display_root(self):
        return str(self.root)

main_app/views.py
from django.shortcuts import render



def index(request, *args, **kwargs):
    return render(request, 'main_app/index.html', context={})

def show_selected(request, *args, **kwargs):
    context = {
        'selected_name': kwargs['selected']
    }

    return render(request, 'main_app/index.html', context=context)

main_app/templates/main_app/index.html
{% extends 'base.html' %}



{% block main %}


{% endblock main %}

main_app/templates/main_app/menu.html
{% load draw_menu %}
{% if to_draw %}

      <ul>
        {% if menu.name == selected_name %}
          <li ><strong><a href="{% url 'main_app:select' url=menu.url selected=menu.name %}">{{ menu.name }}</a></strong></li>
          {% change_context attr='before_selected' new_val=False %}
        {% else %}
        <li><a href="{% url 'main_app:select' url=menu.url selected=menu.name %}">{{ menu.name }}</a></li>
        {% endif %}
        {% if before_selected %}
          {% for child in menu.children.all %}
            {% draw_menu child %}
          {% endfor %}
        {% else %}
          <ul>
            {% for child in menu.children.all %}
              <li><a href="{% url 'main_app:select' url=child.url selected=child.name %}">{{ child.name }}</a></li>
            {% endfor %}
          </ul>
        {% endif %}
      </ul>
{% endif %}

templates/base.html
{% load draw_menu %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>

<div>
    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'main_app:index' %}">Home</a></li>
                </ul>
                {% endblock %}
            </div>
            <div class="description">
                <h1>Menus</h1>
            </div>
            <div class="container">
                <div class="list">
                    {% draw_menu 'Catalog' %}
                </div>
                <div class="list">
                    {% draw_menu 'Room' %}
                </div>
            </div>
        </div>
    </div>

</div>

{% block main %}

{% endblock %}
</body>
</html>